version: '2'

services:
  db:
    image: postgres
    volumes:
      - ./docker/init-psql.sh:/docker-entrypoint-initdb.d/init-psql.sh
    environment:
      - POSTGRES_PASSWORD=posa
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 4000:4000
    environment:
      - PORT=4000
      - MIX_ENV=dev
      - SECRET_KEY_BASE=
      - DATABASE_PASS=posa
      - DATABASE_USER=postgres
      - DATABASE_NAME=posa
      - DATABASE_HOST=db
    depends_on:
      - db
